#cleanup
rm -rf obj_dir
rm -f distributor.vcd

# run Verilator to translate SV to C++, including tb
verilator -Wall -Wno-UNUSED --cc --trace distributor.sv --exe distributor_tb.cpp

# build C++ project via make, automatically generated by Verilator
make -j -C obj_dir/ -f Vdistributor.mk Vdistributor

# run executable sim file
obj_dir/Vdistributor
