// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"

class Vtop__Syms;
class Vtop_queue_new;


class Vtop___024root final : public VerilatedModule {
  public:
    // CELLS
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__0__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__1__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__2__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__3__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__4__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__5__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__6__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__7__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__8__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__9__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__10__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__11__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__12__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__13__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__14__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__15__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__16__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__17__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__18__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__19__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__20__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__21__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__22__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__23__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__24__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__25__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__26__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__27__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__28__KET____DOT__queue_block;
    Vtop_queue_new* __PVT__top__DOT__genblk1__BRA__29__KET____DOT__queue_block;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(ready,0,0);
        VL_OUT8(r,7,0);
        VL_OUT8(g,7,0);
        VL_OUT8(b,7,0);
        VL_OUT8(first,0,0);
        VL_OUT8(last_x,0,0);
        VL_OUT8(last_y,0,0);
        VL_OUT8(valid,0,0);
        CData/*0:0*/ top__DOT__reset_engine;
        CData/*0:0*/ top__DOT__fin_wire;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__0__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__1__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__2__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__3__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__4__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__5__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__6__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__7__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__8__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__9__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__10__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__11__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__12__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__13__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__14__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__15__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__16__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__17__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__18__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__19__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__20__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__21__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__22__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__23__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__24__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__25__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__26__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__27__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__28__KET____DOT__engine__finished;
        CData/*0:0*/ top__DOT____Vcellout__genblk1__BRA__29__KET____DOT__engine__finished;
        CData/*0:0*/ __Vclklast__TOP__clk;
        VL_IN(iterations_max,31,0);
        VL_IN(zoom,31,0);
        VL_IN(x_offset,31,0);
        VL_IN(y_offset,31,0);
        IData/*23:0*/ top__DOT__colour_o_wire;
        IData/*31:0*/ top__DOT__xpixel_wire;
        IData/*31:0*/ top__DOT__ypixel_wire;
        IData/*29:0*/ top__DOT__fin_bus;
        IData/*29:0*/ top__DOT__en_bus;
        IData/*29:0*/ top__DOT__full_queue_bus;
        IData/*29:0*/ top__DOT__match_bus;
        IData/*31:0*/ top__DOT__j;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__0__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__0__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__0__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__1__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__1__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__1__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__2__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__2__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__2__KET____DOT__engine__iterations;
    };
    struct {
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__3__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__3__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__3__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__4__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__4__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__4__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__5__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__5__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__5__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__6__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__6__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__6__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__7__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__7__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__7__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__8__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__8__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__8__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__9__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__9__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__9__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__10__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__10__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__10__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__11__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__11__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__11__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__12__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__12__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__12__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__13__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__13__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__13__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__14__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__14__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__14__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__15__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__15__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__15__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__16__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__16__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__16__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__17__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__17__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__17__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__18__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__18__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__18__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__19__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__19__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__19__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__20__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__20__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__20__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__21__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__21__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__21__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__22__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__22__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__22__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__23__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__23__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__23__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__24__KET____DOT__engine__ypixel;
    };
    struct {
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__24__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__24__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__25__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__25__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__25__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__26__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__26__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__26__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__27__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__27__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__27__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__28__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__28__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__28__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__29__KET____DOT__engine__ypixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__29__KET____DOT__engine__xpixel;
        IData/*31:0*/ top__DOT____Vcellout__genblk1__BRA__29__KET____DOT__engine__iterations;
        IData/*31:0*/ top__DOT__distributor__DOT__x0;
        IData/*31:0*/ top__DOT__distributor__DOT__y0;
        IData/*31:0*/ top__DOT__combinator_block__DOT__xpixel;
        IData/*31:0*/ top__DOT__combinator_block__DOT__ypixel;
        IData/*31:0*/ top__DOT__genblk1__BRA__0__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__0__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__0__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__0__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__0__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__1__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__1__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__1__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__1__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__1__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__2__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__2__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__2__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__2__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__2__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__3__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__3__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__3__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__3__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__3__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__4__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__4__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__4__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__4__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__4__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__5__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__5__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__5__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__5__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__5__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__6__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__6__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__6__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__6__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__6__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__7__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__7__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__7__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__7__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__7__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__8__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__8__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__8__KET____DOT__engine__DOT__state;
    };
    struct {
        IData/*31:0*/ top__DOT__genblk1__BRA__8__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__8__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__9__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__9__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__9__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__9__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__9__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__10__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__10__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__10__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__10__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__10__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__11__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__11__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__11__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__11__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__11__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__12__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__12__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__12__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__12__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__12__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__13__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__13__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__13__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__13__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__13__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__14__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__14__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__14__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__14__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__14__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__15__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__15__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__15__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__15__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__15__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__16__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__16__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__16__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__16__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__16__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__17__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__17__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__17__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__17__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__17__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__18__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__18__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__18__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__18__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__18__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__19__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__19__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__19__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__19__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__19__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__20__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__20__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__20__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__20__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__20__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__21__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__21__KET____DOT__engine__DOT__y0_buff;
    };
    struct {
        IData/*31:0*/ top__DOT__genblk1__BRA__21__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__21__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__21__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__22__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__22__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__22__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__22__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__22__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__23__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__23__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__23__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__23__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__23__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__24__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__24__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__24__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__24__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__24__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__25__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__25__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__25__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__25__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__25__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__26__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__26__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__26__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__26__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__26__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__27__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__27__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__27__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__27__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__27__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__28__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__28__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__28__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__28__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__28__KET____DOT__engine__DOT__y;
        IData/*31:0*/ top__DOT__genblk1__BRA__29__KET____DOT__engine__DOT__x0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__29__KET____DOT__engine__DOT__y0_buff;
        IData/*31:0*/ top__DOT__genblk1__BRA__29__KET____DOT__engine__DOT__state;
        IData/*31:0*/ top__DOT__genblk1__BRA__29__KET____DOT__engine__DOT__x;
        IData/*31:0*/ top__DOT__genblk1__BRA__29__KET____DOT__engine__DOT__y;
        QData/*63:0*/ top__DOT__genblk1__BRA__0__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__0__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__0__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__1__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__1__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__1__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__2__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__2__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__2__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__3__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__3__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__3__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__4__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__4__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__4__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__5__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__5__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__5__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__6__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__6__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__6__KET____DOT__engine__DOT__y2;
    };
    struct {
        QData/*63:0*/ top__DOT__genblk1__BRA__7__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__7__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__7__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__8__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__8__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__8__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__9__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__9__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__9__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__10__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__10__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__10__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__11__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__11__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__11__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__12__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__12__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__12__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__13__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__13__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__13__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__14__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__14__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__14__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__15__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__15__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__15__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__16__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__16__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__16__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__17__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__17__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__17__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__18__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__18__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__18__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__19__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__19__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__19__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__20__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__20__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__20__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__21__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__21__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__21__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__22__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__22__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__22__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__23__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__23__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__23__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__24__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__24__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__24__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__25__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__25__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__25__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__26__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__26__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__26__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__27__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__27__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__27__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__28__KET____DOT__engine__DOT__y_tmp;
    };
    struct {
        QData/*63:0*/ top__DOT__genblk1__BRA__28__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__28__KET____DOT__engine__DOT__y2;
        QData/*63:0*/ top__DOT__genblk1__BRA__29__KET____DOT__engine__DOT__y_tmp;
        QData/*63:0*/ top__DOT__genblk1__BRA__29__KET____DOT__engine__DOT__x2;
        QData/*63:0*/ top__DOT__genblk1__BRA__29__KET____DOT__engine__DOT__y2;
        VlUnpacked<IData/*23:0*/, 30> top__DOT__colour_bus_o;
        VlUnpacked<IData/*31:0*/, 30> top__DOT__x;
        VlUnpacked<IData/*31:0*/, 30> top__DOT__y;
        VlUnpacked<IData/*31:0*/, 30> top__DOT__iterations_bus;
        VlUnpacked<IData/*31:0*/, 30> top__DOT__xpixel_bus;
        VlUnpacked<IData/*31:0*/, 30> top__DOT__ypixel_bus;
        VlUnpacked<IData/*23:0*/, 30> top__DOT__colour_bus_i;
        VlUnpacked<IData/*31:0*/, 30> top__DOT____Vcellout__distributor__y;
        VlUnpacked<IData/*31:0*/, 30> top__DOT____Vcellout__distributor__x;
        VlUnpacked<IData/*23:0*/, 30> top__DOT____Vcellout__lut_rom__rgb_val;
        VlUnpacked<IData/*31:0*/, 30> top__DOT____Vcellinp__lut_rom__iterations;
        VlUnpacked<IData/*23:0*/, 50> top__DOT__lut_rom__DOT__lut_array;
        VlUnpacked<CData/*0:0*/, 5> __Vm_traceActivity;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
